In [1]:
import pandas as pd
import numpy as np

# Import and "corrupt" the original dataframe

In [2]:
"anes_timeseries_2020_csv_20210719.csv"
df_noErr = pd.read_csv("anes_timeseries_2020_csv_20210719.csv")

<ipython-input-2-0f7b19b3063e>:2: DtypeWarning: Columns (15,17,18,19,21,22,23,25,26,27,29,30,31,33,34,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df_noErr = pd.read_csv("anes_timeseries_2020_csv_20210719.csv")

In [3]:
df_noErr

,version,V200001,V160001_orig,V200002,V200003,V200004,V200005,V200006,V200007,V200008,...,V203518,V203519,V203520,V203521,V203522,V203523,V203524,V203525,V203526,V203527
0,ANES2020TimeSeries_20210719,200015,401318,3,2,3,0,-2,-2,-2,...,Thomas Jeffery 'Tom' Cole,1,-1. Inapplicable,-1,-1,82,-1. Inapplicable,-1,-1. Inapplicable,-1
1,ANES2020TimeSeries_20210719,200022,300261,3,2,3,0,4,-1,3,...,Michael Keith 'Mike' Simpson,1,-1. Inapplicable,-1,-1,-1,-1. Inapplicable,-1,-1. Inapplicable,-1
2,ANES2020TimeSeries_20210719,200039,400181,3,2,3,0,-2,-2,-2,...,Scott William Taylor,1,-1. Inapplicable,-1,-1,81,-1. Inapplicable,-1,-1. Inapplicable,-1
3,ANES2020TimeSeries_20210719,200046,300171,3,2,3,0,-2,-2,-2,...,Devin Gerald Nunes,1,-1. Inapplicable,-1,-1,81,-1. Inapplicable,-1,-1. Inapplicable,-1
4,ANES2020TimeSeries_20210719,200053,405145,3,2,3,1,-2,-2,-2,...,Kenneth R. 'Ken' Buck,1,-1. Inapplicable,-1,-1,81,-1. Inapplicable,-1,-1. Inapplicable,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8275,ANES2020TimeSeries_20210719,535315,-1,1,6,3,0,-2,-2,-2,...,Neal Patrick Dunn,1,-1. Inapplicable,-1,-1,82,-1. Inapplicable,-1,-1. Inapplicable,-1
8276,ANES2020TimeSeries_20210719,535360,-1,1,6,3,0,1,1,1,...,Michael Keith 'Mike' Simpson,1,-1. Inapplicable,-1,-1,-1,-1. Inapplicable,-1,-1. Inapplicable,-1
8277,ANES2020TimeSeries_20210719,535414,-1,2,6,3,0,-2,-2,-2,...,Kenneth S. 'Ken' Calvert,1,-1. Inapplicable,-1,-1,81,-1. Inapplicable,-1,-1. Inapplicable,-1
8278,ANES2020TimeSeries_20210719,535421,-1,3,6,3,0,-2,-2,-2,...,Robert J. 'Rob' Wittman,1,-1. Inapplicable,-1,-1,81,-1. Inapplicable,-1,-1. Inapplicable,-1
8279,ANES2020TimeSeries_20210719,535469,-1,1,6,3,0,-2,-2,-2,...,H. Morgan 'Morgan' Griffith,1,-1. Inapplicable,-1,-1,81,-1. Inapplicable,-1,-1. Inapplicable,-1

In [4]:
col2corrupt = "V201336"

for i, el in enumerate(df_noErr[col2corrupt]):
    if el==4:
        r = np.random.rand()
        if r<0.3:
            el2 = '4.0'
        elif r <0.6:
            el2 = "Four"
        else:
            el2 = el
        df_noErr.loc[i,col2corrupt] = el2

In [5]:
df_noErr[col2corrupt].unique()

array([2, 'Four', 1, 3, '4.0', 4, 5, -9, -8], dtype=object)

In [6]:
# Save it
df_noErr.to_csv("anes_errors.csv", sep=';')

# Restart with the dataset

Import the dataset

<font color='orange'>Notice: it is normal that it will raise an error! </font> Indeed, this step is only to show that we need to pay attention when opening the file. You can open it in the right way with the cell after this one

In [7]:
df0 = pd.read_csv("anes_errors.csv")

ParserError: Error tokenizing data. C error: Expected 1 fields in line 16, saw 3

Import the data correctly (i.e. specifying the separator)

In [8]:
df0 = pd.read_csv("anes_errors.csv", sep=';')

<ipython-input-8-ec35da512f52>:1: DtypeWarning: Columns (16,18,19,20,22,23,24,26,27,28,30,31,32,34,35,36,38,39,1509,1510) have mixed types. Specify dtype option on import or set low_memory=False.
  df0 = pd.read_csv("anes_errors.csv", sep=';')

In [9]:
# Visualize the dataframe
df0

,Unnamed: 0,version,V200001,V160001_orig,V200002,V200003,V200004,V200005,V200006,V200007,...,V203518,V203519,V203520,V203521,V203522,V203523,V203524,V203525,V203526,V203527
0,0,ANES2020TimeSeries_20210719,200015,401318,3,2,3,0,-2,-2,...,Thomas Jeffery 'Tom' Cole,1,-1. Inapplicable,-1,-1,82,-1. Inapplicable,-1,-1. Inapplicable,-1
1,1,ANES2020TimeSeries_20210719,200022,300261,3,2,3,0,4,-1,...,Michael Keith 'Mike' Simpson,1,-1. Inapplicable,-1,-1,-1,-1. Inapplicable,-1,-1. Inapplicable,-1
2,2,ANES2020TimeSeries_20210719,200039,400181,3,2,3,0,-2,-2,...,Scott William Taylor,1,-1. Inapplicable,-1,-1,81,-1. Inapplicable,-1,-1. Inapplicable,-1
3,3,ANES2020TimeSeries_20210719,200046,300171,3,2,3,0,-2,-2,...,Devin Gerald Nunes,1,-1. Inapplicable,-1,-1,81,-1. Inapplicable,-1,-1. Inapplicable,-1
4,4,ANES2020TimeSeries_20210719,200053,405145,3,2,3,1,-2,-2,...,Kenneth R. 'Ken' Buck,1,-1. Inapplicable,-1,-1,81,-1. Inapplicable,-1,-1. Inapplicable,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8275,8275,ANES2020TimeSeries_20210719,535315,-1,1,6,3,0,-2,-2,...,Neal Patrick Dunn,1,-1. Inapplicable,-1,-1,82,-1. Inapplicable,-1,-1. Inapplicable,-1
8276,8276,ANES2020TimeSeries_20210719,535360,-1,1,6,3,0,1,1,...,Michael Keith 'Mike' Simpson,1,-1. Inapplicable,-1,-1,-1,-1. Inapplicable,-1,-1. Inapplicable,-1
8277,8277,ANES2020TimeSeries_20210719,535414,-1,2,6,3,0,-2,-2,...,Kenneth S. 'Ken' Calvert,1,-1. Inapplicable,-1,-1,81,-1. Inapplicable,-1,-1. Inapplicable,-1
8278,8278,ANES2020TimeSeries_20210719,535421,-1,3,6,3,0,-2,-2,...,Robert J. 'Rob' Wittman,1,-1. Inapplicable,-1,-1,81,-1. Inapplicable,-1,-1. Inapplicable,-1
8279,8279,ANES2020TimeSeries_20210719,535469,-1,1,6,3,0,-2,-2,...,H. Morgan 'Morgan' Griffith,1,-1. Inapplicable,-1,-1,81,-1. Inapplicable,-1,-1. Inapplicable,-1

### Select the variables to study

Node variables

In [10]:
list_of_node_variables = ['V201336', 'V202257', 'V201417', 'V201312', 'V201416', 'V201262', 'V202337', 'V201258']

df_nodes = df0[list_of_node_variables]

In [11]:
df_nodes

     V201336  V202257  V201417  V201312  V201416  V201262  V202337  V201258
0          2        1        1        2        3        7        3        7
1       Four        3        3        2        1       99        3        4
2       Four        1        4        1        1        1        1        3
3          1        1        1        3        1        1        3       99
4          3        3        2        3        2        4        3        6
...      ...      ...      ...      ...      ...      ...      ...      ...
8275       3        2        2        1        2        4        3        5
8276       4        3        1        1        3        4        3        5
8277       2        3        3        3        1        5        1        4
8278       3        2        3        2        2        5        3        7
8279    Four        1        4        1        1        1        1        1

[8280 rows x 8 columns]

Heat variables

In [12]:
list_of_heat_variables = ['V201157']

df_heat = df0[list_of_heat_variables]

In [13]:
df_heat

      V201157
0          85
1          50
2           0
3          70
4          70
...       ...
8275      100
8276       70
8277       50
8278       70
8279       30

[8280 rows x 1 columns]

### Consistency

I.e. make the naming of the responses consistent

In [14]:
df_nodes["V201336"].unique()

array(['2', 'Four', '1', '3', '4.0', '4', '5', '-9', '-8'], dtype=object)

In [15]:
mask = df_nodes["V201336"]=="Four"
df_nodes.loc[mask, "V201336"] = '4'

mask = df_nodes["V201336"]=="4.0"
df_nodes.loc[mask, "V201336"] = '4'

In [16]:
df_nodes["V201336"].unique()

array(['2', '4', '1', '3', '5', '-9', '-8'], dtype=object)

### Rename the columns

So that we know what we are actually looking at

In [17]:
dic_nodes = {"V201336":"abortion",  "V202257":"income", "V201417":"immigrants",
             "V201312":"welfare","V201416":"gay","V201262":"environment",
             "V202337":"gun", "V201258":"black"}

In [18]:
df_nodes = df_nodes.rename(columns=dic_nodes)

In [19]:
df_nodes

     abortion  income  immigrants  welfare  gay  environment  gun  black
0           2       1           1        2    3            7    3      7
1           4       3           3        2    1           99    3      4
2           4       1           4        1    1            1    1      3
3           1       1           1        3    1            1    3     99
4           3       3           2        3    2            4    3      6
...       ...     ...         ...      ...  ...          ...  ...    ...
8275        3       2           2        1    2            4    3      5
8276        4       3           1        1    3            4    3      5
8277        2       3           3        3    1            5    1      4
8278        3       2           3        2    2            5    3      7
8279        4       1           4        1    1            1    1      1

[8280 rows x 8 columns]

In [20]:
dic_heat = {"V201157":"ThermoRep"}

In [21]:
df_heat = df_heat.rename(columns=dic_heat)

In [22]:
df_heat

      ThermoRep
0            85
1            50
2             0
3            70
4            70
...         ...
8275        100
8276         70
8277         50
8278         70
8279         30

[8280 rows x 1 columns]

### Rename the answers

In [23]:
dic_ans = {"abortion":{"1":"Never","2":"spec.Cases","3":"in_Need","4":"always"},
       "income":{"1":"favor","2":"oppose","3":"neither"},
       "immigrants":{"1":"sendBack","2":"GuestProgram","3":"Requirements","4":"Allow"}, 
       "welfare":{"1":"increased","2":"decreased","3":"same"},
       "gay":{"1":"can_marry","2":"civ.union","3":"no_recognition"},
       "environment":{"1":"More_regul++","2":"More_regul+","3":"More_regul","4":"neut",
                      "5":"Less_regul","6":"Less_regul+","7":"Less_regul++"},
       "gun":{"1":"More_diffic","2":"Easier","3":"Same"},
       "black":{"1":"Help++","2":"Help+","3":"Help","4":"Neut","5":"NoHelp","6":"NoHelp+","7":"NoHelp++"}
          }

In [24]:
for c in df_nodes.columns: 
    df_nodes[c] = df_nodes[c].astype(str)
    df_nodes[c].replace(dic_ans[c], inplace=True)

In [25]:
df_nodes

,abortion,income,immigrants,welfare,gay,environment,gun,black
0,spec.Cases,favor,sendBack,decreased,no_recognition,Less_regul++,Same,NoHelp++
1,always,neither,Requirements,decreased,can_marry,99,Same,Neut
2,always,favor,Allow,increased,can_marry,More_regul++,More_diffic,Help
3,Never,favor,sendBack,same,can_marry,More_regul++,Same,99
4,in_Need,neither,GuestProgram,same,civ.union,neut,Same,NoHelp+
...,...,...,...,...,...,...,...,...
8275,in_Need,oppose,GuestProgram,increased,civ.union,neut,Same,NoHelp
8276,always,neither,sendBack,increased,no_recognition,neut,Same,NoHelp
8277,spec.Cases,neither,Requirements,same,can_marry,Less_regul,More_diffic,Neut
8278,in_Need,oppose,Requirements,decreased,civ.union,Less_regul,Same,NoHelp++
8279,always,favor,Allow,increased,can_marry,More_regul++,More_diffic,Help++

### Set the missing values

Here we are setting all the non-standard values as "Ref" (i.e. we use this as label)

In [26]:
for c in df_nodes.columns:
    mask = []
    line = df_nodes[c]
    dic_ = dic_ans[c]
    for el in line:
        val = not (el in dic_.values())
        mask.append(val)
    mask = np.array(mask)
    df_nodes[c][mask]="Ref"

In [27]:
df_nodes

,abortion,income,immigrants,welfare,gay,environment,gun,black
0,spec.Cases,favor,sendBack,decreased,no_recognition,Less_regul++,Same,NoHelp++
1,always,neither,Requirements,decreased,can_marry,Ref,Same,Neut
2,always,favor,Allow,increased,can_marry,More_regul++,More_diffic,Help
3,Never,favor,sendBack,same,can_marry,More_regul++,Same,Ref
4,in_Need,neither,GuestProgram,same,civ.union,neut,Same,NoHelp+
...,...,...,...,...,...,...,...,...
8275,in_Need,oppose,GuestProgram,increased,civ.union,neut,Same,NoHelp
8276,always,neither,sendBack,increased,no_recognition,neut,Same,NoHelp
8277,spec.Cases,neither,Requirements,same,can_marry,Less_regul,More_diffic,Neut
8278,in_Need,oppose,Requirements,decreased,civ.union,Less_regul,Same,NoHelp++
8279,always,favor,Allow,increased,can_marry,More_regul++,More_diffic,Help++

# Make the dummy-coded dataframe

In [28]:
df_dummy = pd.DataFrame()
df = df_nodes.copy() # Select the dataframe of the nodes

list_of_columns = df_nodes.columns # here you can select a subset of columns


for col in list_of_columns: # For each column...
    values = (df[col].unique()) # ... get the list of the possible responses (i.e. nodes)
    
    for value in values: # For each response
        if type(value) == str: # check if the answer is type string
            name = str(col)+":"+str(value) # get the names as col:response
            df_dummy[name] = df[col] == value # get dummy-coded column

        else:
            if np.isnan(value): # if it's a refused answer
                name = str(col)+":"+"Ref" 
                df_dummy[name] = np.isnan(df[col])
            else: # Otherwise
                name = str(col)+":"+str(value) 
                df_dummy[name] = df[col] == value

In [29]:
df_dummy

,abortion:spec.Cases,abortion:always,abortion:Never,abortion:in_Need,abortion:Ref,income:favor,income:neither,income:oppose,income:Ref,immigrants:sendBack,...,gun:Easier,gun:Ref,black:NoHelp++,black:Neut,black:Help,black:Ref,black:NoHelp+,black:Help++,black:Help+,black:NoHelp
0,True,False,False,False,False,True,False,False,False,True,...,False,False,True,False,False,False,False,False,False,False
1,False,True,False,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2,False,True,False,False,False,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,False,False,True,False,False,True,False,False,False,True,...,False,False,False,False,False,True,False,False,False,False
4,False,False,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8275,False,False,False,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True
8276,False,True,False,False,False,False,True,False,False,True,...,False,False,False,False,False,False,False,False,False,True
8277,True,False,False,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
8278,False,False,False,True,False,False,False,True,False,False,...,False,False,True,False,False,False,False,False,False,False
8279,False,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

# Make the network (simplified version)

This section is just for understanding the working principle of the code. In the next section you will have the same code but much more complete. Feel free to use the one that you prefer!

In [30]:
# Import the required packages
import networkx as nx
import scipy.stats as stt

In [31]:
def make_graph_simplified(df):
    
    G = nx.Graph()
    list_of_nodes = df.columns

    for node_i in list_of_nodes:
        for node_j in list_of_nodes:

            # Get the two columns
            c1 = df[node_i]
            c2 = df[node_j]
            
            (r,p) = stt.spearmanr(c1,c2)
            if r<0:
                r = 0
            
            if r>0:
                G.add_weighted_edges_from([(node_i,node_j,r)],weight='weight')
    
    return G

In [32]:
# Make the graph
G = make_graph_simplified(df_dummy)

In [33]:
# Save it
filename = 'ANES_simplified'
nx.write_gexf(G,filename+'.gexf')

# Make the network (complete version)

### Support functions

In [34]:
def phi_(n11,n00,n10,n01):
    n1p = n11+n10
    n0p = n01+n00
    np1 = n01+n11
    np0 = n10+n00
    
    num = n11*n00-n10*n01
    den_ = n1p*n0p*np0*np1
    
    if den_==0:
        phi_=np.nan
    else:
        phi_ = num/np.sqrt(den_)
    return phi_

In [35]:
def p_val(r,L):
    den = np.sqrt(1-r**2)
    deg_free = L-2
    if den==0:
        p = 0
    else:
        num = r*np.sqrt(deg_free)
        t = num/den
        p = stt.t.sf(abs(t), df=deg_free)*2
    return p

In [36]:
def phi(x,y,get_p=False):
    
    m_eq = x==y
    m_diff = np.logical_not(m_eq)
    
    n11 = float(np.sum(x[m_eq]==True))
    n00 = float(np.sum(x[m_eq]==False))
    
    n10 = float(np.sum(x[m_diff]==True))
    n01 = float(np.sum(y[m_diff]==True))
    
    phi_val = phi_(n11,n00,n10,n01)
    
    if get_p:
        p = p_val(phi_val,len(x))
        return phi_val, p
    else:
        return phi_val

### Main function

In [37]:
def make_graph_(df, list_of_nodes, alpha=0.05, get_p=True, remove_nan=False, remove_non_significant=False, exclude_same_question=True, print_=False):
    
    if get_p==False and remove_non_significant==True:
        print("Warning: Setting remove_non_significant to False as get_p is False!")
        remove_non_significant=False
    
    G = nx.Graph()
    
    count = 0
    for i, node_i in enumerate(list_of_nodes):
        for j, node_j in enumerate(list_of_nodes):
            
            if j <= i: # do not run the same couple twice
                continue
            
            if print_:
                count += 1
                l = len(list_of_nodes)
                n_tot = l*(l-1)/2
                print(count,"/",n_tot, " = ", np.round(count/n_tot,decimals=2)*100, '%')
                
            basename1 = node_i.split(sep=':')[0]
            basename2 = node_j.split(sep=':')[0]
            
            if exclude_same_question:
                if basename1 == basename2: # if they belong to the same item
                    continue

            # Get the two columns
            c1 = df[node_i]
            c2 = df[node_j]
            
            if remove_nan:
                if ("Ref" in node_i) or ("Ref" in node_j):
                    continue
                
                c1_n = df[basename1+":Ref"] # get the refused values of each item
                c2_n = df[basename2+":Ref"]
                
                mask = np.logical_not(np.logical_or(c1_n, c2_n)) # get a mask of the refused values
                
                c1 = c1[mask] # select only the non-nan element
                c2 = c2[mask]
            
            if get_p:
                (r,p) = phi(c1,c2, get_p=True)
            else:
                r = phi(c1,c2, get_p=False)
            
            # Check if there are the conditions for drawing a node
            if remove_non_significant: 
                condition = r>0 and p<alpha
            else:
                condition = r>0

            if condition:
                G.add_weighted_edges_from([(node_i,node_j,r)],weight='weight')
                if get_p:
                    G.add_weighted_edges_from([(node_i,node_j,p)],weight='p')
                    sig = float(p<alpha) # Boolean are not accepted as edge weight
                    G.add_weighted_edges_from([(node_i,node_j,sig)],weight='sig')
    return G

### Make the network from the dummy-coded dataframe

In [39]:
# Parameters
remove_nan=True
get_p=True
remove_non_significant=False
alpha=0.05

# Get the graph
G = make_graph_(df=df_dummy, list_of_nodes=df_dummy.columns, alpha=alpha, get_p=get_p, remove_non_significant=remove_non_significant, 
                remove_nan=remove_nan, exclude_same_question=True, print_=True)
print("Complete!")

1 / 861.0  =  0.0 %
2 / 861.0  =  0.0 %
3 / 861.0  =  0.0 %
4 / 861.0  =  0.0 %
5 / 861.0  =  1.0 %
6 / 861.0  =  1.0 %
7 / 861.0  =  1.0 %
8 / 861.0  =  1.0 %
9 / 861.0  =  1.0 %
10 / 861.0  =  1.0 %
11 / 861.0  =  1.0 %
12 / 861.0  =  1.0 %
13 / 861.0  =  2.0 %
14 / 861.0  =  2.0 %
15 / 861.0  =  2.0 %
16 / 861.0  =  2.0 %
17 / 861.0  =  2.0 %
18 / 861.0  =  2.0 %
19 / 861.0  =  2.0 %
20 / 861.0  =  2.0 %
21 / 861.0  =  2.0 %
22 / 861.0  =  3.0 %
23 / 861.0  =  3.0 %
24 / 861.0  =  3.0 %
25 / 861.0  =  3.0 %
26 / 861.0  =  3.0 %
27 / 861.0  =  3.0 %
28 / 861.0  =  3.0 %
29 / 861.0  =  3.0 %
30 / 861.0  =  3.0 %
31 / 861.0  =  4.0 %
32 / 861.0  =  4.0 %
33 / 861.0  =  4.0 %
34 / 861.0  =  4.0 %
35 / 861.0  =  4.0 %
36 / 861.0  =  4.0 %
37 / 861.0  =  4.0 %
38 / 861.0  =  4.0 %
39 / 861.0  =  5.0 %
40 / 861.0  =  5.0 %
41 / 861.0  =  5.0 %
42 / 861.0  =  5.0 %
43 / 861.0  =  5.0 %
44 / 861.0  =  5.0 %
45 / 861.0  =  5.0 %
46 / 861.0  =  5.0 %
47 / 861.0  =  5.0 %
48 / 861.0  =  6.0 %
49 / 861.0  =  6.0 %
50 / 861.0  =  6.0 %
51 / 861.0  =  6.0 %
52 / 861.0  =  6.0 %
53 / 861.0  =  6.0 %
54 / 861.0  =  6.0 %
55 / 861.0  =  6.0 %
56 / 861.0  =  7.000000000000001 %
57 / 861.0  =  7.000000000000001 %
58 / 861.0  =  7.000000000000001 %
59 / 861.0  =  7.000000000000001 %
60 / 861.0  =  7.000000000000001 %
61 / 861.0  =  7.000000000000001 %
62 / 861.0  =  7.000000000000001 %
63 / 861.0  =  7.000000000000001 %
64 / 861.0  =  7.000000000000001 %
65 / 861.0  =  8.0 %
66 / 861.0  =  8.0 %
67 / 861.0  =  8.0 %
68 / 861.0  =  8.0 %
69 / 861.0  =  8.0 %
70 / 861.0  =  8.0 %
71 / 861.0  =  8.0 %
72 / 861.0  =  8.0 %
73 / 861.0  =  8.0 %
74 / 861.0  =  9.0 %
75 / 861.0  =  9.0 %
76 / 861.0  =  9.0 %
77 / 861.0  =  9.0 %
78 / 861.0  =  9.0 %
79 / 861.0  =  9.0 %
80 / 861.0  =  9.0 %
81 / 861.0  =  9.0 %
82 / 861.0  =  10.0 %
83 / 861.0  =  10.0 %
84 / 861.0  =  10.0 %
85 / 861.0  =  10.0 %
86 / 861.0  =  10.0 %
87 / 861.0  =  10.0 %
88 / 861.0  =  10.0 %
89 / 861.0  =  10.0 %
90 / 861.0  =  10.0 %
91 / 861.0  =  11.0 %
92 / 861.0  =  11.0 %
93 / 861.0  =  11.0 %
94 / 861.0  =  11.0 %
95 / 861.0  =  11.0 %
96 / 861.0  =  11.0 %
97 / 861.0  =  11.0 %
98 / 861.0  =  11.0 %
99 / 861.0  =  11.0 %
100 / 861.0  =  12.0 %
101 / 861.0  =  12.0 %
102 / 861.0  =  12.0 %
103 / 861.0  =  12.0 %
104 / 861.0  =  12.0 %
105 / 861.0  =  12.0 %
106 / 861.0  =  12.0 %
107 / 861.0  =  12.0 %
108 / 861.0  =  13.0 %
109 / 861.0  =  13.0 %
110 / 861.0  =  13.0 %
111 / 861.0  =  13.0 %
112 / 861.0  =  13.0 %
113 / 861.0  =  13.0 %
114 / 861.0  =  13.0 %
115 / 861.0  =  13.0 %
116 / 861.0  =  13.0 %
117 / 861.0  =  14.000000000000002 %
118 / 861.0  =  14.000000000000002 %
119 / 861.0  =  14.000000000000002 %
120 / 861.0  =  14.000000000000002 %
121 / 861.0  =  14.000000000000002 %
122 / 861.0  =  14.000000000000002 %
123 / 861.0  =  14.000000000000002 %
124 / 861.0  =  14.000000000000002 %
125 / 861.0  =  15.0 %
126 / 861.0  =  15.0 %
127 / 861.0  =  15.0 %
128 / 861.0  =  15.0 %
129 / 861.0  =  15.0 %
130 / 861.0  =  15.0 %
131 / 861.0  =  15.0 %
132 / 861.0  =  15.0 %
133 / 861.0  =  15.0 %
134 / 861.0  =  16.0 %
135 / 861.0  =  16.0 %
136 / 861.0  =  16.0 %
137 / 861.0  =  16.0 %
138 / 861.0  =  16.0 %
139 / 861.0  =  16.0 %
140 / 861.0  =  16.0 %
141 / 861.0  =  16.0 %
142 / 861.0  =  16.0 %
143 / 861.0  =  17.0 %
144 / 861.0  =  17.0 %
145 / 861.0  =  17.0 %
146 / 861.0  =  17.0 %
147 / 861.0  =  17.0 %
148 / 861.0  =  17.0 %
149 / 861.0  =  17.0 %
150 / 861.0  =  17.0 %
151 / 861.0  =  18.0 %
152 / 861.0  =  18.0 %
153 / 861.0  =  18.0 %
154 / 861.0  =  18.0 %
155 / 861.0  =  18.0 %
156 / 861.0  =  18.0 %
157 / 861.0  =  18.0 %
158 / 861.0  =  18.0 %
159 / 861.0  =  18.0 %
160 / 861.0  =  19.0 %
161 / 861.0  =  19.0 %
162 / 861.0  =  19.0 %
163 / 861.0  =  19.0 %
164 / 861.0  =  19.0 %
165 / 861.0  =  19.0 %
166 / 861.0  =  19.0 %
167 / 861.0  =  19.0 %
168 / 861.0  =  20.0 %
169 / 861.0  =  20.0 %
170 / 861.0  =  20.0 %
171 / 861.0  =  20.0 %
172 / 861.0  =  20.0 %
173 / 861.0  =  20.0 %
174 / 861.0  =  20.0 %
175 / 861.0  =  20.0 %
176 / 861.0  =  20.0 %
177 / 861.0  =  21.0 %
178 / 861.0  =  21.0 %
179 / 861.0  =  21.0 %
180 / 861.0  =  21.0 %
181 / 861.0  =  21.0 %
182 / 861.0  =  21.0 %
183 / 861.0  =  21.0 %
184 / 861.0  =  21.0 %
185 / 861.0  =  21.0 %
186 / 861.0  =  22.0 %
187 / 861.0  =  22.0 %
188 / 861.0  =  22.0 %
189 / 861.0  =  22.0 %
190 / 861.0  =  22.0 %
191 / 861.0  =  22.0 %
192 / 861.0  =  22.0 %
193 / 861.0  =  22.0 %
194 / 861.0  =  23.0 %
195 / 861.0  =  23.0 %
196 / 861.0  =  23.0 %
197 / 861.0  =  23.0 %
198 / 861.0  =  23.0 %
199 / 861.0  =  23.0 %
200 / 861.0  =  23.0 %
201 / 861.0  =  23.0 %
202 / 861.0  =  23.0 %
203 / 861.0  =  24.0 %
204 / 861.0  =  24.0 %
205 / 861.0  =  24.0 %
206 / 861.0  =  24.0 %
207 / 861.0  =  24.0 %
208 / 861.0  =  24.0 %
209 / 861.0  =  24.0 %
210 / 861.0  =  24.0 %
211 / 861.0  =  25.0 %
212 / 861.0  =  25.0 %
213 / 861.0  =  25.0 %
214 / 861.0  =  25.0 %
215 / 861.0  =  25.0 %
216 / 861.0  =  25.0 %
217 / 861.0  =  25.0 %
218 / 861.0  =  25.0 %
219 / 861.0  =  25.0 %
220 / 861.0  =  26.0 %
221 / 861.0  =  26.0 %
222 / 861.0  =  26.0 %
223 / 861.0  =  26.0 %
224 / 861.0  =  26.0 %
225 / 861.0  =  26.0 %
226 / 861.0  =  26.0 %
227 / 861.0  =  26.0 %
228 / 861.0  =  26.0 %
229 / 861.0  =  27.0 %
230 / 861.0  =  27.0 %
231 / 861.0  =  27.0 %
232 / 861.0  =  27.0 %
233 / 861.0  =  27.0 %
234 / 861.0  =  27.0 %
235 / 861.0  =  27.0 %
236 / 861.0  =  27.0 %
237 / 861.0  =  28.000000000000004 %
238 / 861.0  =  28.000000000000004 %
239 / 861.0  =  28.000000000000004 %
240 / 861.0  =  28.000000000000004 %
241 / 861.0  =  28.000000000000004 %
242 / 861.0  =  28.000000000000004 %
243 / 861.0  =  28.000000000000004 %
244 / 861.0  =  28.000000000000004 %
245 / 861.0  =  28.000000000000004 %
246 / 861.0  =  28.999999999999996 %
247 / 861.0  =  28.999999999999996 %
248 / 861.0  =  28.999999999999996 %
249 / 861.0  =  28.999999999999996 %
250 / 861.0  =  28.999999999999996 %
251 / 861.0  =  28.999999999999996 %
252 / 861.0  =  28.999999999999996 %
253 / 861.0  =  28.999999999999996 %
254 / 861.0  =  30.0 %
255 / 861.0  =  30.0 %
256 / 861.0  =  30.0 %
257 / 861.0  =  30.0 %
258 / 861.0  =  30.0 %
259 / 861.0  =  30.0 %
260 / 861.0  =  30.0 %
261 / 861.0  =  30.0 %
262 / 861.0  =  30.0 %
263 / 861.0  =  31.0 %
264 / 861.0  =  31.0 %
265 / 861.0  =  31.0 %
266 / 861.0  =  31.0 %
267 / 861.0  =  31.0 %
268 / 861.0  =  31.0 %
269 / 861.0  =  31.0 %
270 / 861.0  =  31.0 %
271 / 861.0  =  31.0 %
272 / 861.0  =  32.0 %
273 / 861.0  =  32.0 %
274 / 861.0  =  32.0 %
275 / 861.0  =  32.0 %
276 / 861.0  =  32.0 %
277 / 861.0  =  32.0 %
278 / 861.0  =  32.0 %
279 / 861.0  =  32.0 %
280 / 861.0  =  33.0 %
281 / 861.0  =  33.0 %
282 / 861.0  =  33.0 %
283 / 861.0  =  33.0 %
284 / 861.0  =  33.0 %
285 / 861.0  =  33.0 %
286 / 861.0  =  33.0 %
287 / 861.0  =  33.0 %
288 / 861.0  =  33.0 %
289 / 861.0  =  34.0 %
290 / 861.0  =  34.0 %
291 / 861.0  =  34.0 %
292 / 861.0  =  34.0 %
293 / 861.0  =  34.0 %
294 / 861.0  =  34.0 %
295 / 861.0  =  34.0 %
296 / 861.0  =  34.0 %
297 / 861.0  =  34.0 %
298 / 861.0  =  35.0 %
299 / 861.0  =  35.0 %
300 / 861.0  =  35.0 %
301 / 861.0  =  35.0 %
302 / 861.0  =  35.0 %
303 / 861.0  =  35.0 %
304 / 861.0  =  35.0 %
305 / 861.0  =  35.0 %
306 / 861.0  =  36.0 %
307 / 861.0  =  36.0 %
308 / 861.0  =  36.0 %
309 / 861.0  =  36.0 %
310 / 861.0  =  36.0 %
311 / 861.0  =  36.0 %
312 / 861.0  =  36.0 %
313 / 861.0  =  36.0 %
314 / 861.0  =  36.0 %
315 / 861.0  =  37.0 %
316 / 861.0  =  37.0 %
317 / 861.0  =  37.0 %
318 / 861.0  =  37.0 %
319 / 861.0  =  37.0 %
320 / 861.0  =  37.0 %
321 / 861.0  =  37.0 %
322 / 861.0  =  37.0 %
323 / 861.0  =  38.0 %
324 / 861.0  =  38.0 %
325 / 861.0  =  38.0 %
326 / 861.0  =  38.0 %
327 / 861.0  =  38.0 %
328 / 861.0  =  38.0 %
329 / 861.0  =  38.0 %
330 / 861.0  =  38.0 %
331 / 861.0  =  38.0 %
332 / 861.0  =  39.0 %
333 / 861.0  =  39.0 %
334 / 861.0  =  39.0 %
335 / 861.0  =  39.0 %
336 / 861.0  =  39.0 %
337 / 861.0  =  39.0 %
338 / 861.0  =  39.0 %
339 / 861.0  =  39.0 %
340 / 861.0  =  39.0 %
341 / 861.0  =  40.0 %
342 / 861.0  =  40.0 %
343 / 861.0  =  40.0 %
344 / 861.0  =  40.0 %
345 / 861.0  =  40.0 %
346 / 861.0  =  40.0 %
347 / 861.0  =  40.0 %
348 / 861.0  =  40.0 %
349 / 861.0  =  41.0 %
350 / 861.0  =  41.0 %
351 / 861.0  =  41.0 %
352 / 861.0  =  41.0 %
353 / 861.0  =  41.0 %
354 / 861.0  =  41.0 %

355 / 861.0  =  41.0 %
356 / 861.0  =  41.0 %
357 / 861.0  =  41.0 %
358 / 861.0  =  42.0 %
359 / 861.0  =  42.0 %
360 / 861.0  =  42.0 %
361 / 861.0  =  42.0 %
362 / 861.0  =  42.0 %
363 / 861.0  =  42.0 %
364 / 861.0  =  42.0 %
365 / 861.0  =  42.0 %
366 / 861.0  =  43.0 %
367 / 861.0  =  43.0 %
368 / 861.0  =  43.0 %
369 / 861.0  =  43.0 %
370 / 861.0  =  43.0 %
371 / 861.0  =  43.0 %
372 / 861.0  =  43.0 %
373 / 861.0  =  43.0 %
374 / 861.0  =  43.0 %
375 / 861.0  =  44.0 %
376 / 861.0  =  44.0 %
377 / 861.0  =  44.0 %
378 / 861.0  =  44.0 %
379 / 861.0  =  44.0 %
380 / 861.0  =  44.0 %
381 / 861.0  =  44.0 %
382 / 861.0  =  44.0 %
383 / 861.0  =  44.0 %
384 / 861.0  =  45.0 %
385 / 861.0  =  45.0 %
386 / 861.0  =  45.0 %
387 / 861.0  =  45.0 %
388 / 861.0  =  45.0 %
389 / 861.0  =  45.0 %
390 / 861.0  =  45.0 %
391 / 861.0  =  45.0 %
392 / 861.0  =  46.0 %
393 / 861.0  =  46.0 %
394 / 861.0  =  46.0 %
395 / 861.0  =  46.0 %
396 / 861.0  =  46.0 %
397 / 861.0  =  46.0 %
398 / 861.0  =  46.0 %
399 / 861.0  =  46.0 %
400 / 861.0  =  46.0 %
401 / 861.0  =  47.0 %
402 / 861.0  =  47.0 %
403 / 861.0  =  47.0 %
404 / 861.0  =  47.0 %
405 / 861.0  =  47.0 %
406 / 861.0  =  47.0 %
407 / 861.0  =  47.0 %
408 / 861.0  =  47.0 %
409 / 861.0  =  48.0 %
410 / 861.0  =  48.0 %
411 / 861.0  =  48.0 %
412 / 861.0  =  48.0 %
413 / 861.0  =  48.0 %
414 / 861.0  =  48.0 %
415 / 861.0  =  48.0 %
416 / 861.0  =  48.0 %
417 / 861.0  =  48.0 %
418 / 861.0  =  49.0 %
419 / 861.0  =  49.0 %
420 / 861.0  =  49.0 %
421 / 861.0  =  49.0 %
422 / 861.0  =  49.0 %
423 / 861.0  =  49.0 %
424 / 861.0  =  49.0 %
425 / 861.0  =  49.0 %
426 / 861.0  =  49.0 %
427 / 861.0  =  50.0 %
428 / 861.0  =  50.0 %
429 / 861.0  =  50.0 %
430 / 861.0  =  50.0 %
431 / 861.0  =  50.0 %
432 / 861.0  =  50.0 %
433 / 861.0  =  50.0 %
434 / 861.0  =  50.0 %
435 / 861.0  =  51.0 %
436 / 861.0  =  51.0 %
437 / 861.0  =  51.0 %
438 / 861.0  =  51.0 %
439 / 861.0  =  51.0 %
440 / 861.0  =  51.0 %
441 / 861.0  =  51.0 %
442 / 861.0  =  51.0 %
443 / 861.0  =  51.0 %
444 / 861.0  =  52.0 %
445 / 861.0  =  52.0 %
446 / 861.0  =  52.0 %
447 / 861.0  =  52.0 %
448 / 861.0  =  52.0 %
449 / 861.0  =  52.0 %
450 / 861.0  =  52.0 %
451 / 861.0  =  52.0 %
452 / 861.0  =  52.0 %
453 / 861.0  =  53.0 %
454 / 861.0  =  53.0 %
455 / 861.0  =  53.0 %
456 / 861.0  =  53.0 %
457 / 861.0  =  53.0 %
458 / 861.0  =  53.0 %
459 / 861.0  =  53.0 %
460 / 861.0  =  53.0 %
461 / 861.0  =  54.0 %
462 / 861.0  =  54.0 %
463 / 861.0  =  54.0 %
464 / 861.0  =  54.0 %
465 / 861.0  =  54.0 %
466 / 861.0  =  54.0 %
467 / 861.0  =  54.0 %
468 / 861.0  =  54.0 %
469 / 861.0  =  54.0 %
470 / 861.0  =  55.00000000000001 %
471 / 861.0  =  55.00000000000001 %
472 / 861.0  =  55.00000000000001 %
473 / 861.0  =  55.00000000000001 %
474 / 861.0  =  55.00000000000001 %
475 / 861.0  =  55.00000000000001 %
476 / 861.0  =  55.00000000000001 %
477 / 861.0  =  55.00000000000001 %
478 / 861.0  =  56.00000000000001 %
479 / 861.0  =  56.00000000000001 %
480 / 861.0  =  56.00000000000001 %
481 / 861.0  =  56.00000000000001 %
482 / 861.0  =  56.00000000000001 %
483 / 861.0  =  56.00000000000001 %
484 / 861.0  =  56.00000000000001 %
485 / 861.0  =  56.00000000000001 %
486 / 861.0  =  56.00000000000001 %
487 / 861.0  =  56.99999999999999 %
488 / 861.0  =  56.99999999999999 %
489 / 861.0  =  56.99999999999999 %
490 / 861.0  =  56.99999999999999 %
491 / 861.0  =  56.99999999999999 %
492 / 861.0  =  56.99999999999999 %
493 / 861.0  =  56.99999999999999 %
494 / 861.0  =  56.99999999999999 %
495 / 861.0  =  56.99999999999999 %
496 / 861.0  =  57.99999999999999 %
497 / 861.0  =  57.99999999999999 %
498 / 861.0  =  57.99999999999999 %
499 / 861.0  =  57.99999999999999 %
500 / 861.0  =  57.99999999999999 %
501 / 861.0  =  57.99999999999999 %
502 / 861.0  =  57.99999999999999 %
503 / 861.0  =  57.99999999999999 %
504 / 861.0  =  59.0 %
505 / 861.0  =  59.0 %
506 / 861.0  =  59.0 %
507 / 861.0  =  59.0 %
508 / 861.0  =  59.0 %
509 / 861.0  =  59.0 %
510 / 861.0  =  59.0 %
511 / 861.0  =  59.0 %
512 / 861.0  =  59.0 %
513 / 861.0  =  60.0 %
514 / 861.0  =  60.0 %
515 / 861.0  =  60.0 %
516 / 861.0  =  60.0 %
517 / 861.0  =  60.0 %
518 / 861.0  =  60.0 %
519 / 861.0  =  60.0 %
520 / 861.0  =  60.0 %
521 / 861.0  =  61.0 %
522 / 861.0  =  61.0 %
523 / 861.0  =  61.0 %
524 / 861.0  =  61.0 %
525 / 861.0  =  61.0 %
526 / 861.0  =  61.0 %
527 / 861.0  =  61.0 %
528 / 861.0  =  61.0 %
529 / 861.0  =  61.0 %
530 / 861.0  =  62.0 %
531 / 861.0  =  62.0 %
532 / 861.0  =  62.0 %
533 / 861.0  =  62.0 %
534 / 861.0  =  62.0 %
535 / 861.0  =  62.0 %
536 / 861.0  =  62.0 %
537 / 861.0  =  62.0 %
538 / 861.0  =  62.0 %
539 / 861.0  =  63.0 %
540 / 861.0  =  63.0 %
541 / 861.0  =  63.0 %
542 / 861.0  =  63.0 %
543 / 861.0  =  63.0 %
544 / 861.0  =  63.0 %
545 / 861.0  =  63.0 %
546 / 861.0  =  63.0 %
547 / 861.0  =  64.0 %
548 / 861.0  =  64.0 %
549 / 861.0  =  64.0 %
550 / 861.0  =  64.0 %
551 / 861.0  =  64.0 %
552 / 861.0  =  64.0 %
553 / 861.0  =  64.0 %
554 / 861.0  =  64.0 %
555 / 861.0  =  64.0 %
556 / 861.0  =  65.0 %
557 / 861.0  =  65.0 %
558 / 861.0  =  65.0 %
559 / 861.0  =  65.0 %
560 / 861.0  =  65.0 %
561 / 861.0  =  65.0 %
562 / 861.0  =  65.0 %
563 / 861.0  =  65.0 %
564 / 861.0  =  66.0 %
565 / 861.0  =  66.0 %
566 / 861.0  =  66.0 %
567 / 861.0  =  66.0 %
568 / 861.0  =  66.0 %
569 / 861.0  =  66.0 %
570 / 861.0  =  66.0 %
571 / 861.0  =  66.0 %
572 / 861.0  =  66.0 %
573 / 861.0  =  67.0 %
574 / 861.0  =  67.0 %
575 / 861.0  =  67.0 %
576 / 861.0  =  67.0 %
577 / 861.0  =  67.0 %
578 / 861.0  =  67.0 %
579 / 861.0  =  67.0 %
580 / 861.0  =  67.0 %
581 / 861.0  =  67.0 %
582 / 861.0  =  68.0 %
583 / 861.0  =  68.0 %
584 / 861.0  =  68.0 %
585 / 861.0  =  68.0 %
586 / 861.0  =  68.0 %
587 / 861.0  =  68.0 %
588 / 861.0  =  68.0 %
589 / 861.0  =  68.0 %
590 / 861.0  =  69.0 %
591 / 861.0  =  69.0 %
592 / 861.0  =  69.0 %
593 / 861.0  =  69.0 %
594 / 861.0  =  69.0 %
595 / 861.0  =  69.0 %
596 / 861.0  =  69.0 %
597 / 861.0  =  69.0 %
598 / 861.0  =  69.0 %
599 / 861.0  =  70.0 %
600 / 861.0  =  70.0 %
601 / 861.0  =  70.0 %
602 / 861.0  =  70.0 %
603 / 861.0  =  70.0 %
604 / 861.0  =  70.0 %
605 / 861.0  =  70.0 %
606 / 861.0  =  70.0 %
607 / 861.0  =  70.0 %
608 / 861.0  =  71.0 %
609 / 861.0  =  71.0 %
610 / 861.0  =  71.0 %
611 / 861.0  =  71.0 %
612 / 861.0  =  71.0 %
613 / 861.0  =  71.0 %
614 / 861.0  =  71.0 %
615 / 861.0  =  71.0 %
616 / 861.0  =  72.0 %
617 / 861.0  =  72.0 %
618 / 861.0  =  72.0 %
619 / 861.0  =  72.0 %
620 / 861.0  =  72.0 %
621 / 861.0  =  72.0 %
622 / 861.0  =  72.0 %
623 / 861.0  =  72.0 %
624 / 861.0  =  72.0 %
625 / 861.0  =  73.0 %
626 / 861.0  =  73.0 %
627 / 861.0  =  73.0 %
628 / 861.0  =  73.0 %
629 / 861.0  =  73.0 %
630 / 861.0  =  73.0 %
631 / 861.0  =  73.0 %
632 / 861.0  =  73.0 %
633 / 861.0  =  74.0 %
634 / 861.0  =  74.0 %
635 / 861.0  =  74.0 %
636 / 861.0  =  74.0 %
637 / 861.0  =  74.0 %
638 / 861.0  =  74.0 %
639 / 861.0  =  74.0 %
640 / 861.0  =  74.0 %
641 / 861.0  =  74.0 %
642 / 861.0  =  75.0 %
643 / 861.0  =  75.0 %
644 / 861.0  =  75.0 %
645 / 861.0  =  75.0 %
646 / 861.0  =  75.0 %
647 / 861.0  =  75.0 %
648 / 861.0  =  75.0 %
649 / 861.0  =  75.0 %
650 / 861.0  =  75.0 %
651 / 861.0  =  76.0 %
652 / 861.0  =  76.0 %
653 / 861.0  =  76.0 %
654 / 861.0  =  76.0 %
655 / 861.0  =  76.0 %
656 / 861.0  =  76.0 %
657 / 861.0  =  76.0 %
658 / 861.0  =  76.0 %
659 / 861.0  =  77.0 %
660 / 861.0  =  77.0 %
661 / 861.0  =  77.0 %
662 / 861.0  =  77.0 %
663 / 861.0  =  77.0 %
664 / 861.0  =  77.0 %
665 / 861.0  =  77.0 %
666 / 861.0  =  77.0 %
667 / 861.0  =  77.0 %
668 / 861.0  =  78.0 %
669 / 861.0  =  78.0 %
670 / 861.0  =  78.0 %
671 / 861.0  =  78.0 %
672 / 861.0  =  78.0 %
673 / 861.0  =  78.0 %
674 / 861.0  =  78.0 %
675 / 861.0  =  78.0 %
676 / 861.0  =  79.0 %
677 / 861.0  =  79.0 %
678 / 861.0  =  79.0 %
679 / 861.0  =  79.0 %
680 / 861.0  =  79.0 %
681 / 861.0  =  79.0 %
682 / 861.0  =  79.0 %
683 / 861.0  =  79.0 %
684 / 861.0  =  79.0 %
685 / 861.0  =  80.0 %
686 / 861.0  =  80.0 %
687 / 861.0  =  80.0 %
688 / 861.0  =  80.0 %
689 / 861.0  =  80.0 %
690 / 861.0  =  80.0 %
691 / 861.0  =  80.0 %
692 / 861.0  =  80.0 %
693 / 861.0  =  80.0 %
694 / 861.0  =  81.0 %
695 / 861.0  =  81.0 %
696 / 861.0  =  81.0 %
697 / 861.0  =  81.0 %
698 / 861.0  =  81.0 %
699 / 861.0  =  81.0 %
700 / 861.0  =  81.0 %
701 / 861.0  =  81.0 %
702 / 861.0  =  82.0 %
703 / 861.0  =  82.0 %
704 / 861.0  =  82.0 %
705 / 861.0  =  82.0 %
706 / 861.0  =  82.0 %
707 / 861.0  =  82.0 %
708 / 861.0  =  82.0 %
709 / 861.0  =  82.0 %
710 / 861.0  =  82.0 %
711 / 861.0  =  83.0 %
712 / 861.0  =  83.0 %
713 / 861.0  =  83.0 %
714 / 861.0  =  83.0 %
715 / 861.0  =  83.0 %
716 / 861.0  =  83.0 %
717 / 861.0  =  83.0 %
718 / 861.0  =  83.0 %
719 / 861.0  =  84.0 %
720 / 861.0  =  84.0 %
721 / 861.0  =  84.0 %
722 / 861.0  =  84.0 %
723 / 861.0  =  84.0 %
724 / 861.0  =  84.0 %
725 / 861.0  =  84.0 %
726 / 861.0  =  84.0 %
727 / 861.0  =  84.0 %
728 / 861.0  =  85.0 %
729 / 861.0  =  85.0 %
730 / 861.0  =  85.0 %
731 / 861.0  =  85.0 %
732 / 861.0  =  85.0 %
733 / 861.0  =  85.0 %
734 / 861.0  =  85.0 %
735 / 861.0  =  85.0 %
736 / 861.0  =  85.0 %
737 / 861.0  =  86.0 %
738 / 861.0  =  86.0 %
739 / 861.0  =  86.0 %
740 / 861.0  =  86.0 %
741 / 861.0  =  86.0 %
742 / 861.0  =  86.0 %
743 / 861.0  =  86.0 %
744 / 861.0  =  86.0 %
745 / 861.0  =  87.0 %
746 / 861.0  =  87.0 %
747 / 861.0  =  87.0 %
748 / 861.0  =  87.0 %
749 / 861.0  =  87.0 %
750 / 861.0  =  87.0 %
751 / 861.0  =  87.0 %
752 / 861.0  =  87.0 %
753 / 861.0  =  87.0 %
754 / 861.0  =  88.0 %
755 / 861.0  =  88.0 %
756 / 861.0  =  88.0 %
757 / 861.0  =  88.0 %
758 / 861.0  =  88.0 %
759 / 861.0  =  88.0 %
760 / 861.0  =  88.0 %
761 / 861.0  =  88.0 %
762 / 861.0  =  89.0 %
763 / 861.0  =  89.0 %
764 / 861.0  =  89.0 %
765 / 861.0  =  89.0 %
766 / 861.0  =  89.0 %
767 / 861.0  =  89.0 %
768 / 861.0  =  89.0 %
769 / 861.0  =  89.0 %
770 / 861.0  =  89.0 %
771 / 861.0  =  90.0 %
772 / 861.0  =  90.0 %
773 / 861.0  =  90.0 %
774 / 861.0  =  90.0 %
775 / 861.0  =  90.0 %
776 / 861.0  =  90.0 %
777 / 861.0  =  90.0 %
778 / 861.0  =  90.0 %

779 / 861.0  =  90.0 %
780 / 861.0  =  91.0 %
781 / 861.0  =  91.0 %
782 / 861.0  =  91.0 %
783 / 861.0  =  91.0 %
784 / 861.0  =  91.0 %
785 / 861.0  =  91.0 %
786 / 861.0  =  91.0 %
787 / 861.0  =  91.0 %
788 / 861.0  =  92.0 %
789 / 861.0  =  92.0 %
790 / 861.0  =  92.0 %
791 / 861.0  =  92.0 %
792 / 861.0  =  92.0 %
793 / 861.0  =  92.0 %
794 / 861.0  =  92.0 %
795 / 861.0  =  92.0 %
796 / 861.0  =  92.0 %
797 / 861.0  =  93.0 %
798 / 861.0  =  93.0 %
799 / 861.0  =  93.0 %
800 / 861.0  =  93.0 %
801 / 861.0  =  93.0 %
802 / 861.0  =  93.0 %
803 / 861.0  =  93.0 %
804 / 861.0  =  93.0 %
805 / 861.0  =  93.0 %
806 / 861.0  =  94.0 %
807 / 861.0  =  94.0 %
808 / 861.0  =  94.0 %
809 / 861.0  =  94.0 %
810 / 861.0  =  94.0 %
811 / 861.0  =  94.0 %
812 / 861.0  =  94.0 %
813 / 861.0  =  94.0 %
814 / 861.0  =  95.0 %
815 / 861.0  =  95.0 %
816 / 861.0  =  95.0 %
817 / 861.0  =  95.0 %
818 / 861.0  =  95.0 %
819 / 861.0  =  95.0 %
820 / 861.0  =  95.0 %
821 / 861.0  =  95.0 %
822 / 861.0  =  95.0 %
823 / 861.0  =  96.0 %
824 / 861.0  =  96.0 %
825 / 861.0  =  96.0 %
826 / 861.0  =  96.0 %
827 / 861.0  =  96.0 %
828 / 861.0  =  96.0 %
829 / 861.0  =  96.0 %
830 / 861.0  =  96.0 %
831 / 861.0  =  97.0 %
832 / 861.0  =  97.0 %
833 / 861.0  =  97.0 %
834 / 861.0  =  97.0 %
835 / 861.0  =  97.0 %
836 / 861.0  =  97.0 %
837 / 861.0  =  97.0 %
838 / 861.0  =  97.0 %
839 / 861.0  =  97.0 %
840 / 861.0  =  98.0 %
841 / 861.0  =  98.0 %
842 / 861.0  =  98.0 %
843 / 861.0  =  98.0 %
844 / 861.0  =  98.0 %
845 / 861.0  =  98.0 %
846 / 861.0  =  98.0 %
847 / 861.0  =  98.0 %
848 / 861.0  =  98.0 %
849 / 861.0  =  99.0 %
850 / 861.0  =  99.0 %
851 / 861.0  =  99.0 %
852 / 861.0  =  99.0 %
853 / 861.0  =  99.0 %
854 / 861.0  =  99.0 %
855 / 861.0  =  99.0 %
856 / 861.0  =  99.0 %
857 / 861.0  =  100.0 %
858 / 861.0  =  100.0 %
859 / 861.0  =  100.0 %
860 / 861.0  =  100.0 %
861 / 861.0  =  100.0 %
Complete!

Save

In [40]:
filename = 'ANES_complete'
nx.write_gexf(G,filename+'.gexf')

# Make heatmap

Make the heatmap using the average

In [41]:
dic_ = dict()

col_heat = df_heat["ThermoRep"] # select the heat variable

for node in G.nodes: # for each node
    col_node = df_dummy[node]

    val = np.nanmean(col_heat[col_node])
    
    dic_[node] = val

nx.set_node_attributes(G, dic_, "ThermoRep_mean")

In [42]:
def corr_nan(x,y):
    x = np.array(x)
    y = np.array(y)
    
    m = np.isnan(x) + np.isnan(y)
    mm = np.logical_not(m)
    
    [r,p] = stt.pearsonr(x[mm],y[mm])
    
    return (r,p)

In [43]:
dic_ = dict()

type_="standard" #"sign"

col_heat = df_heat["ThermoRep"]

for node in G.nodes:
    col_node = df_dummy[node]

    (r,p) = corr_nan(col_node,col_heat)

    if type_=="sign":
        dic_[node] = np.sign(r)
    elif type_=="standard":
        dic_[node] = r

nx.set_node_attributes(G, dic_, "ThermoRep")

In [46]:
dic_ = dict()

type_="sign" #"sign"

col_heat = df_heat["ThermoRep"]

for node in G.nodes:
    col_node = df_dummy[node]

    (r,p) = corr_nan(col_node,col_heat)

    if type_=="sign":
        dic_[node] = np.sign(r)
    elif type_=="standard":
        dic_[node] = r

nx.set_node_attributes(G, dic_, "ThermoRep_signed")

In [47]:
filename = 'ANES_final'
nx.write_gexf(G,filename+'.gexf')

### Manually exploring the network

In [45]:
node1 = "environment:Less_regul++"
node2 = "black:NoHelp"
G.get_edge_data(node1,node2)

{'weight': 0.004292419135647908, 'p': 0.7249416154833359, 'sig': 0.0}

### Finding the x and y component of the nodes

In [69]:
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [70]:
pos = nx.spring_layout(G,iterations=5000) # Get the positions with the spring layout

# Restructure the data type
pos2 = [[],[]]
key_list = [] # ordered list of the nodes
for key in pos:
    pos2[0].append(pos[key][0])
    pos2[1].append(pos[key][1])
    key_list.append(key)

# Use PCA to rotate the network in such a way that the x-axis is the main one
pos3 = []
for key in pos:
    pos3.append([pos[key][0],pos[key][1]])

pca = PCA(n_components=2)
pca.fit(pos3)
x_pca = pca.transform(pos3)

# Get the x and y position of each node
xx = x_pca[:,0]
yy = x_pca[:,1]

Correlation between x coordinate and feeling thermometer

In [71]:
dict_term = nx.get_node_attributes(G,"ThermoRep_mean") # get the feeling thermo
thermo = [dict_term[key] for key in key_list]
stt.spearmanr(xx,thermo)

SpearmanrResult(correlation=-0.9538579067990832, pvalue=2.7866095518760973e-18)

# Quantitative analysis of clusters

In [72]:
clust1 = ["environment:More_regul++",
"environment:More_regul+",
"abortion:always",
"income:favor",
"immigrants:Allow",
"welfare:increased",
"gay:can_marry",
"gun:More_diffic",
"black:Help++",
"black:Help+"]

clust2 = ["welfare:decreased",
'abortion:spec.Cases',
'income:neither',
'income:oppose',
'immigrants:sendBack',
'immigrants:GuestProgram',
'gay:no_recognition',
'gay:civ.union',
'environment:Less_regul++',
'environment:neut',
'environment:Less_regul',
'environment:Less_regul+',
'gun:Same',
'gun:Easier',
'black:NoHelp++',
'black:NoHelp+',
'black:NoHelp',
'abortion:Never',
'abortion:in_Need']

In [82]:
def get_mean_corr(df_,cl):
    corrs = []
    for i1, el1 in enumerate(cl):
        for i2, el2 in enumerate(cl):
            if i1>i2:
                line1 = df_[el1]
                line2 = df_[el2]
                r = phi(line1,line2, get_p=False)
                corrs.append(r)
    return np.mean(corrs)

In [85]:
print("Coherence clust 1: ", get_mean_corr(df_dummy, clust1))
print("Coherence clust 2: ", get_mean_corr(df_dummy, clust2))

Coherence clust 1:  0.2077054934257627
Coherence clust 2:  0.0707711880591039

### Bootstrap it!

In [87]:
N_rep = 100

M1 = []
M2 = []

df_len = len(df_dummy)

for i in range(N_rep):
    
    index_t = (np.random.rand(df_len)*(df_len-1)).astype(int) # generate the list
    
    df_t = df_dummy.iloc[index_t]
    
    m1 = get_mean_corr(df_t, clust1)
    m2 = get_mean_corr(df_t, clust2)
    
    M1.append(m1)
    M2.append(m2)

In [96]:
# Print the 10-90 % interval
print("Clust1: ", np.round(np.percentile(M1,10),3), "-", np.round(np.percentile(M1,90),3))
print("Clust2: ", np.round(np.percentile(M2,10),3), "-", np.round(np.percentile(M2,90),3))

Clust1:  0.203 - 0.211
Clust2:  0.069 - 0.072

In [89]:
tests = np.array(M1)>np.array(M2)
np.sum(tests)/len(tests)

1.0

In [97]:
tests = np.array(M1)<=np.array(M2)
np.sum(tests)/len(tests)

0.0